name: JMH Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21', '25' ]
        threads: ['1', '10']
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Run JMH benchmarks
        env:
          VERIPRIMER_PACKAGES_USER: ${{ secrets.VERIPRIMER_PACKAGES_USER }}
          VERIPRIMER_PACKAGES_TOKEN: ${{ secrets.VERIPRIMER_PACKAGES_TOKEN }}
        run: ./gradlew jmh -PjavaVersion=${{ matrix.java }} -Pjmh.threads=${{ matrix.threads }}

      - name: Rename benchmark results
        run: mv build/reports/jmh/results.json build/reports/jmh/java-${{ matrix.java }}-threads-${{ matrix.threads }}.json

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ matrix.java }}-threads-${{ matrix.threads }}
          path: build/reports/jmh/java-${{ matrix.java }}-threads-${{ matrix.threads }}.json

      - name: Update Gist with benchmark results
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          FILE_PATH="build/reports/jmh/java-${{ matrix.java }}-threads-${{ matrix.threads }}.json"
          GIST_FILENAME="java-${{ matrix.java }}-threads-${{ matrix.threads }}.json"
          
          if gh gist view ${{ secrets.GIST_ID }} --files | grep -q "^${GIST_FILENAME}$"; then
            echo "File exists in Gist, updating..."
            gh gist edit ${{ secrets.GIST_ID }} "${FILE_PATH}" --filename "${GIST_FILENAME}"
          else
            echo "File does not exist in Gist, adding..."
            gh gist edit ${{ secrets.GIST_ID }} --add "${FILE_PATH}"
          fi

  aggregate-results:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download benchmark results
        uses: actions/download-artifact@v4
        with:
          path: benchmark-results

      - name: Display structure of downloaded files
        run: ls -R benchmark-results

      - name: Move results to a single folder
        run: |
          mkdir aggregated-results
          find benchmark-results -type f -name "*.json" -exec mv -t aggregated-results/ {} +

      - name: Display structure of aggregated results
        run: ls -R aggregated-results

      - name: Create zip archive
        run: zip -r aggregated-benchmark-results.zip aggregated-results

      - name: Upload aggregated results
        uses: actions/upload-artifact@v4
        with:
          name: aggregated-benchmark-results
          path: aggregated-benchmark-results.zip
